apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
  - name: nginx2
    image: dsaucez/upf
  nodeName: master-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upf-deployment
  labels:
    app: upf
spec:
  replicas: 4
  selector:
    matchLabels:
      app: upf
  template:
    metadata:
      labels:
        app: upf
        app.kubernetes.io/name: proxy
    spec:
      containers:
      - name: upf
        image: dsaucez/upf
        ports:
        - containerPort: 8080
          protocol: UDP
          name: udp-upf-port
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - upf
            topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: upf-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: udp-upf-service-port
    protocol: UDP
    port: 8080
    targetPort: udp-upf-port
